/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package supportbank;
import java.io.*;
import java.util.Scanner;


public class App {



    public class Account{
        public String Name;
        public double MoneyFromBank=0;

        public void addMoneyToBank(double amountToAdd){
            this.MoneyFromBank+=amountToAdd;
        }
        public void reduceMoneyInBank(double amountToAdd){
            this.MoneyFromBank+=amountToAdd;
        }

        public Account(String Name){
            this.Name=Name;
        }


    }




        public static void main(String[] args) throws Exception
        {

            boolean skip = true;
            String line = "";
            String splitBy = ",";
            try
            {
//parsing a CSV file into BufferedReader class constructor
                BufferedReader br = new BufferedReader(new FileReader("/home/andrej/IdeaProjects/SupportBank-Java/SupportBank-Java/Transactions2014.csv"));
                while ((line = br.readLine()) != null)
                {
                    if(skip) {
                        skip = false; // Skip only the first line
                        continue;
                    }
                    String[] employee = line.split(splitBy);
                    System.out.println("[Date=" + employee[0] + ", From=" + employee[1] + ", To=" + employee[2] + ", Narrative=" + employee[3] + ", Amount= " + employee[4] + "]");
                }
            }
            catch (IOException e)
            {
                e.printStackTrace();
            }
        }


}
