/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package supportbank;

import java.io.*;
import java.text.NumberFormat;
import java.util.*;
import java.util.Scanner;  // Import the Scanner class
import java.util.regex.Matcher;


public class App {


    public static void main(String[] args) throws Exception {


        BankingSystem bankingSystem = new BankingSystem();
        HashMap<String, String> hash_map = new HashMap<String, String>();
        boolean skip = true;
        String line = "";
        String splitBy = ",";
        try {
            //parsing a CSV file into BufferedReader class constructor
            BufferedReader br = new BufferedReader(new FileReader("/home/andrej/IdeaProjects/SupportBank-Java/SupportBank-Java/Transactions2014.csv"));
            while ((line = br.readLine()) != null) {
                if (skip) {
                    skip = false; // Skip only the first line
                    continue;
                }
                String[] dataInTheLine = line.split(splitBy);

                String date = dataInTheLine[0].trim();
                String from = dataInTheLine[1].trim();
                String to = dataInTheLine[2].trim();
                String narrative = dataInTheLine[3].trim();
                Double amount = Double.parseDouble(dataInTheLine[4].trim());


                bankingSystem.createAccount(from);
                bankingSystem.createAccount(to);
                bankingSystem.makeTransaction(date, from, to, narrative, amount);


            }
        } catch (IOException e) {
            e.printStackTrace();
        }


        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the command: (List all or List of transactions)");
        String userInput = sc.nextLine();


        if ("List all".equals(userInput)) {
            bankingSystem.listALl();
        } else if ("List of transactions".equals(userInput)) {
            System.out.println("Input person name: ");
            String name = sc.nextLine();
            bankingSystem.getAccounts().get(name).printAllTransaction();
        } else {
            System.out.println("command not found");
        }


    }
}




